# Exported from Render on 2025-04-21T08:44:03Z
services:
- type: web
  name: n8n
  runtime: image
  image:
    url: docker.n8n.io/n8nio/n8n:latest
  plan: free
  envVars:
  - key: N8N_EDITOR_BASE_URL
    value: https://n8n-0x7f.onrender.com
  - key: WEBHOOK_URL
    value: https://n8n-0x7f.onrender.com
  - key: N8N_PROTOCOL
    value: https
  - key: N8N_PORT
    value: "443"
  - key: N8N_HOST
    value: n8n-0x7f.onrender.com
  region: oregon
version: "1"
